plugins:
  - jekyll-seo-tag

url: moonloot.co

image: /assets/images/giveaway-promo.jpg

logo: /assets/images/moonloot-logo-dark-purple.svg

twitter:
  username: moonlootco
  card: summary

social:
  - https://twitter.com/moonlootco

kramdown:
  parse_block_html: true
